name: petclinic-be
namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: eks-delivery.aws.main.edp.projects.epam.com


database:
  required: true
  version: postgres:9.6
  storageClass: gp2
  capacity: 1Gi



ingress:
  required: true
  site: petclinic-be
  path: /api

image:
  name: petclinic-be
  version: latest